const products = [
  {
    _id: "1",
    name: "Full Zip running Shirts",
    image: "img/new/fine lady.jpg",
    price: 70,
    brand: "Nzoski",
    rating: 4.5,
    numReviews: 10,
    countInStock: 6,
  },
  {
    _id: "1",
    name: "Full Zip running Shirts",
    image: "img/Clothes/tobias-tullius-Fg15LdqpWrs-unsplash.jpg",
    price: 60,
    brand: "Nzoski",
    rating: 4.5,
    numReviews: 10,
    countInStock: 6,
  },
  {
    _id: "1",
    name: "Full Zip running Shirts",
    image: "img/Clothes/tobias-tullius-Fg15LdqpWrs-unsplash.jpg",
    price: 60,
    brand: "Nzoski",
    rating: 4.5,
    numReviews: 10,
    countInStock: 6,
  },
  {
    _id: "1",
    name: "Full Zip running Shirts",
    image: "img/Clothes/ryan-hoffman-6Nub980bI3I-unsplash.jpg",
    price: 60,
    brand: "Nzoski",
    rating: 4.5,
    numReviews: 10,
    countInStock: 6,
  },
  {
    _id: "1",
    name: "Full Zip running Shirts",
    image: "img/new/fine lady.jpg",
    price: 60,
    brand: "Nzoski",
    rating: 4.5,
    numReviews: 10,
    countInStock: 6,
  },
  {
    _id: "1",
    name: "Full Zip running Shirts",
    image: "img/new/fine lady.jpg",
    price: 60,
    brand: "Nzoski",
    rating: 4.5,
    numReviews: 10,
    countInStock: 6,
  },
];

export default products;
